### ISSUE TITLE
Error something went wrong during the migration OSX

### ISSUE THREAD

**Issue by FranOjedaCMusic** [d-fi/releases#8]
Hello there, I updated bc i was getting the deezer doesn't have the song anymore error but i get this one now

Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. ReferenceError: Cannot access 'config' before initialization

    at Conf._migrate (/snapshot/d-fi/node_modules/conf/dist/source/index.js:407:23)
    at new Conf (/snapshot/d-fi/node_modules/conf/dist/source/index.js:144:18)
    at Object.<anonymous> (/snapshot/d-fi/src/config.js:39:16)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)

I don't program at all sorry if its a noob question

**Comment by ev-w** [comment]
Same issue here on macOS, whether installing via npm or using the pre-built binary

**Comment by necrevistonnezr** [comment]
It's the same on Windows, seems some paths are hardcoded? Because "C:\snapshot" does not exist on my machine

```
pkg/prelude/bootstrap.js:1244
      throw error;
      ^
Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. ReferenceError: Cannot access 'config' before initialization
    at Conf._migrate (C:\snapshot\d-fi\node_modules\conf\dist\source\index.js:407:23)
    at new Conf (C:\snapshot\d-fi\node_modules\conf\dist\source\index.js:144:18)
    at Object.<anonymous> (C:\snapshot\d-fi\src\config.js:39:16)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
```

**Comment by necrevistonnezr** [comment]
Installin from scratch in Ubuntu via NPM works

**Comment by sayem314** [comment]
Sorry guys. It was a nasty mistake with a variable name. Fixed and updated. Go, download the new version.
